version: 0.1
lint:
  definitions:
    - name: terraform-docs
      files: [terraform]

      commands:
        - name: check terraform-docs
          output: pass_fail
          success_codes: [0, 1]
          read_output_from: stderr
          run: terraform-docs ${target} -c ${workspace}/.trunk/configs/.terraform-docs.yml --output-check
          run_from: ${target_directory}
          target: ${parent}
        - name: generate all terraform-docs
          files: [terraform]
          output: stdout
          success_codes: [0]
          formatter: true
          read_output_from: stdout
          run: terraform-docs ${target} -c ${workspace}/.trunk/configs/.terraform-docs.yml
          run_from: ${target_directory}
          target: ${parent}
      tools:
        - terraform-docs
  enabled:
    - terraform-docs-check
    - terraform-docs-generate
  exported_configs:
    - configs/.terraform-docs.yaml
tools:
  enabled:
    - terraform-docs@0.18.0
