version: 0.1
lint:
  definitions:
    - name: terraform-docs
      files: [terraform]

      commands:
        - name: check
          files: [terraform]
          output: pass_fail
          success_codes: [0, 1]
          read_output_from: stderr
          run: terraform-docs . -c ${workspace}/.trunk/configs/.terraform-docs.yml --output-check
          run_from: ${target_directory}
          target: ${parent}
        - name: generate
          files: [terraform]
          output: pass_fail
          success_codes: [0, 1]
          formatter: true
          read_output_from: stdout
          run: terraform-docs ${target} -c ${workspace}/.trunk/configs/.terraform-docs.yml
          run_from: ${target_directory}
          target: ${parent}
          in_place: true
      tools:
        - terraform-docs
  exported_configs:
    - configs:
        - configs/.terraform-docs.yaml
        - terraform-docs-elements/header.md
        - terraform-docs-elements/footer.md
# tools:
#   enabled:
#     - terraform-docs@0.18.0
