version: 0.1
lint:
  definitions:
    - name: terraform-docs
      files: [terraform]

      commands:
        - name: check
          disable_upstream: true
          files: [terraform]
          run: terraform-docs ${target} -c ${workspace}/.trunk/configs/.terraform-docs.yaml --output-check
          read_output_from: stderr
          success_codes: [0, 1]
          output: pass_fail
          target: ${parent}

        - name: generate
          enabled: false # Disabled because we seemingly cannot edit the file in place without conflicting with other linters.
          files: [terraform]
          formatter: true
          in_place: true
          run: terraform-docs ${target} -c ${workspace}/.trunk/configs/.terraform-docs.yaml
          success_codes: [0, 1]
          output: pass_fail
          read_output_from: stderr
          target: ${parent}
      direct_configs:
        - configs/.terraform-docs.yml
      suggest_if: files_present
      tools:
        - terraform-docs
      version_command:
        parse_regex: ${semver}
        run: terraform-docs --version
  exported_configs:
    - configs:
        - configs/.terraform-docs.yaml
        - terraform-docs-elements/header.md
        - terraform-docs-elements/footer.md

actions:
  definitions:
    - id: generate-terraform-docs
      run: .trunk/tools/terraform-docs -c ${workspace}/.trunk/configs/.terraform-docs.yaml --recursive .
