version: 0.1
lint:
  definitions:
    - name: terraform-docs
      files: [terraform]

      commands:
        - name: check
          files: [terraform]
          run: terraform-docs ${target} -c ${workspace}/.trunk/configs/.terraform-docs.yml --output-check
          read_output_from: stderr
          success_codes: [0, 1]
          output: pass_fail
          target: ${parent}

        # - name: generate
        #   files: [terraform]
        #   formatter: true
        #   in_place: true
        #   run: terraform-docs ${target} -c ${workspace}/.trunk/configs/.terraform-docs.yml
        #   success_codes: [0, 1]
        #   output: pass_fail
        #   read_output_from: stderr
        #   target: ${parent}
      tools:
        - terraform-docs
  exported_configs:
    - configs:
        - configs/.terraform-docs.yaml
        - terraform-docs-elements/header.md
        - terraform-docs-elements/footer.md
